# Generated by Django 4.1.2 on 2023-06-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarro', models.AutoField(db_column='idCarro', primary_key=True, serialize=False)),
                ('nombreCli', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('fecha_emicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('idConsola', models.AutoField(db_column='idConsola', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idGame', models.AutoField(db_column='idJuego', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/clientes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ap_paterno',
            field=models.CharField(max_length=30, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='guests.genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
