# Generated by Django 4.1.2 on 2023-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
