# Generated by Django 4.1.2 on 2023-06-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_last_login_alter_guest_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Cliente',
        ),
    ]
