# Generated by Django 4.1.2 on 2023-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarro', models.AutoField(db_column='idCarro', primary_key=True, serialize=False)),
                ('nombreCli', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('fecha_emicion', models.DateField()),
            ],
        ),
    ]
