# Generated by Django 4.1.2 on 2023-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cadenaJuegos',
            field=models.CharField(default='', max_length=100, verbose_name='Cadena de Ids de Juegos'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
