# Generated by Django 4.1.2 on 2023-07-06 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='dias_renta',
            field=models.IntegerField(default=3, verbose_name='Dias que dura la renta'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_emicion',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
    ]
