# Generated by Django 4.1.2 on 2023-06-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('idConsola', models.IntegerField(db_column='idConsola', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGame', models.IntegerField(verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default='juegos/Game_Default.jpg', null=True, upload_to='juegos')),
                ('stock', models.IntegerField(default=1)),
                ('precio', models.IntegerField(default=100)),
                ('idConsola', models.ForeignKey(db_column='idConsola', on_delete=django.db.models.deletion.CASCADE, to='administrador.consola', verbose_name='Consola')),
            ],
        ),
        migrations.AddConstraint(
            model_name='juego',
            constraint=models.UniqueConstraint(fields=('idGame', 'idConsola'), name='pk_idg_idc'),
        ),
    ]
