# Generated by Django 4.1.2 on 2023-06-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='juego',
            name='idGame',
            field=models.IntegerField(verbose_name='idGame'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
