# Generated by Django 4.1.2 on 2023-06-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_juego_imagen_url_alter_juego_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
