# Generated by Django 4.1.2 on 2023-06-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_delete_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGame', models.IntegerField(verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos')),
                ('imagen_url', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField(default=1)),
                ('precio', models.IntegerField(default=100)),
                ('idConsola', models.ForeignKey(db_column='idConsola', on_delete=django.db.models.deletion.CASCADE, to='administrador.consola', verbose_name='Consola')),
            ],
        ),
        migrations.AddConstraint(
            model_name='juego',
            constraint=models.UniqueConstraint(fields=('idGame',), name='pk_idg_idc'),
        ),
    ]
